// 300+ major publicly traded companies — S&P 500 core + key large-caps
// Format: { symbol, name }

export interface StockEntry {
    symbol: string;
    name: string;
}

export const STOCK_LIST: StockEntry[] = [
    { symbol: "AAPL", name: "Apple Inc." },
    { symbol: "MSFT", name: "Microsoft Corporation" },
    { symbol: "AMZN", name: "Amazon.com Inc." },
    { symbol: "NVDA", name: "NVIDIA Corporation" },
    { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
    { symbol: "GOOG", name: "Alphabet Inc. Class C" },
    { symbol: "META", name: "Meta Platforms Inc." },
    { symbol: "TSLA", name: "Tesla Inc." },
    { symbol: "BRK.B", name: "Berkshire Hathaway Class B" },
    { symbol: "UNH", name: "UnitedHealth Group" },
    { symbol: "LLY", name: "Eli Lilly and Company" },
    { symbol: "JPM", name: "JPMorgan Chase & Co." },
    { symbol: "V", name: "Visa Inc." },
    { symbol: "XOM", name: "Exxon Mobil Corporation" },
    { symbol: "AVGO", name: "Broadcom Inc." },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "MA", name: "Mastercard Inc." },
    { symbol: "PG", name: "Procter & Gamble Co." },
    { symbol: "HD", name: "The Home Depot Inc." },
    { symbol: "COST", name: "Costco Wholesale Corp." },
    { symbol: "MRK", name: "Merck & Co. Inc." },
    { symbol: "ABBV", name: "AbbVie Inc." },
    { symbol: "CVX", name: "Chevron Corporation" },
    { symbol: "CRM", name: "Salesforce Inc." },
    { symbol: "KO", name: "The Coca-Cola Company" },
    { symbol: "NFLX", name: "Netflix Inc." },
    { symbol: "AMD", name: "Advanced Micro Devices Inc." },
    { symbol: "PEP", name: "PepsiCo Inc." },
    { symbol: "BAC", name: "Bank of America Corp." },
    { symbol: "TMO", name: "Thermo Fisher Scientific" },
    { symbol: "ADBE", name: "Adobe Inc." },
    { symbol: "WMT", name: "Walmart Inc." },
    { symbol: "LIN", name: "Linde plc" },
    { symbol: "MCD", name: "McDonald's Corporation" },
    { symbol: "CSCO", name: "Cisco Systems Inc." },
    { symbol: "ABT", name: "Abbott Laboratories" },
    { symbol: "ACN", name: "Accenture plc" },
    { symbol: "ORCL", name: "Oracle Corporation" },
    { symbol: "DHR", name: "Danaher Corporation" },
    { symbol: "TXN", name: "Texas Instruments Inc." },
    { symbol: "CMCSA", name: "Comcast Corporation" },
    { symbol: "PM", name: "Philip Morris International" },
    { symbol: "INTC", name: "Intel Corporation" },
    { symbol: "VZ", name: "Verizon Communications" },
    { symbol: "NKE", name: "NIKE Inc." },
    { symbol: "NEE", name: "NextEra Energy Inc." },
    { symbol: "IBM", name: "International Business Machines" },
    { symbol: "RTX", name: "RTX Corporation" },
    { symbol: "INTU", name: "Intuit Inc." },
    { symbol: "UNP", name: "Union Pacific Corporation" },
    { symbol: "NOW", name: "ServiceNow Inc." },
    { symbol: "QCOM", name: "Qualcomm Inc." },
    { symbol: "SPGI", name: "S&P Global Inc." },
    { symbol: "HON", name: "Honeywell International" },
    { symbol: "GE", name: "General Electric Co." },
    { symbol: "AMGN", name: "Amgen Inc." },
    { symbol: "CAT", name: "Caterpillar Inc." },
    { symbol: "AMAT", name: "Applied Materials Inc." },
    { symbol: "LOW", name: "Lowe's Companies Inc." },
    { symbol: "BA", name: "The Boeing Company" },
    { symbol: "GS", name: "Goldman Sachs Group" },
    { symbol: "T", name: "AT&T Inc." },
    { symbol: "BKNG", name: "Booking Holdings Inc." },
    { symbol: "BLK", name: "BlackRock Inc." },
    { symbol: "DE", name: "Deere & Company" },
    { symbol: "PFE", name: "Pfizer Inc." },
    { symbol: "ELV", name: "Elevance Health Inc." },
    { symbol: "MDT", name: "Medtronic plc" },
    { symbol: "ISRG", name: "Intuitive Surgical Inc." },
    { symbol: "ADP", name: "Automatic Data Processing" },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
    { symbol: "SYK", name: "Stryker Corporation" },
    { symbol: "LMT", name: "Lockheed Martin Corp." },
    { symbol: "MDLZ", name: "Mondelez International" },
    { symbol: "GILD", name: "Gilead Sciences Inc." },
    { symbol: "PLD", name: "Prologis Inc." },
    { symbol: "MMC", name: "Marsh & McLennan" },
    { symbol: "AXP", name: "American Express Co." },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
    { symbol: "CI", name: "The Cigna Group" },
    { symbol: "DIS", name: "The Walt Disney Company" },
    { symbol: "ADI", name: "Analog Devices Inc." },
    { symbol: "ETN", name: "Eaton Corporation plc" },
    { symbol: "CVS", name: "CVS Health Corporation" },
    { symbol: "PANW", name: "Palo Alto Networks" },
    { symbol: "ZTS", name: "Zoetis Inc." },
    { symbol: "MO", name: "Altria Group Inc." },
    { symbol: "C", name: "Citigroup Inc." },
    { symbol: "BDX", name: "Becton Dickinson" },
    { symbol: "SNPS", name: "Synopsys Inc." },
    { symbol: "CDNS", name: "Cadence Design Systems" },
    { symbol: "SO", name: "The Southern Company" },
    { symbol: "DUK", name: "Duke Energy Corporation" },
    { symbol: "CL", name: "Colgate-Palmolive Co." },
    { symbol: "CME", name: "CME Group Inc." },
    { symbol: "WM", name: "Waste Management Inc." },
    { symbol: "FI", name: "Fiserv Inc." },
    { symbol: "TGT", name: "Target Corporation" },
    { symbol: "MCO", name: "Moody's Corporation" },
    { symbol: "BSX", name: "Boston Scientific Corp." },
    { symbol: "ITW", name: "Illinois Tool Works Inc." },
    { symbol: "NOC", name: "Northrop Grumman Corp." },
    { symbol: "EOG", name: "EOG Resources Inc." },
    { symbol: "KLAC", name: "KLA Corporation" },
    { symbol: "PH", name: "Parker-Hannifin Corp." },
    { symbol: "USB", name: "U.S. Bancorp" },
    { symbol: "ICE", name: "Intercontinental Exchange" },
    { symbol: "SHW", name: "Sherwin-Williams Co." },
    { symbol: "APD", name: "Air Products & Chemicals" },
    { symbol: "FCX", name: "Freeport-McMoRan Inc." },
    { symbol: "GD", name: "General Dynamics Corp." },
    { symbol: "AON", name: "Aon plc" },
    { symbol: "PNC", name: "PNC Financial Services" },
    { symbol: "LRCX", name: "Lam Research Corp." },
    { symbol: "MPC", name: "Marathon Petroleum Corp." },
    { symbol: "TJX", name: "TJX Companies Inc." },
    { symbol: "MCHP", name: "Microchip Technology" },
    { symbol: "HCA", name: "HCA Healthcare Inc." },
    { symbol: "COP", name: "ConocoPhillips" },
    { symbol: "EMR", name: "Emerson Electric Co." },
    { symbol: "NSC", name: "Norfolk Southern Corp." },
    { symbol: "AJG", name: "Arthur J. Gallagher" },
    { symbol: "ABNB", name: "Airbnb Inc." },
    { symbol: "SLB", name: "Schlumberger Limited" },
    { symbol: "CARR", name: "Carrier Global Corp." },
    { symbol: "TDG", name: "TransDigm Group" },
    { symbol: "PSA", name: "Public Storage" },
    { symbol: "NXPI", name: "NXP Semiconductors" },
    { symbol: "ORLY", name: "O'Reilly Automotive" },
    { symbol: "AZO", name: "AutoZone Inc." },
    { symbol: "MSI", name: "Motorola Solutions" },
    { symbol: "FTNT", name: "Fortinet Inc." },
    { symbol: "CEG", name: "Constellation Energy" },
    { symbol: "PYPL", name: "PayPal Holdings Inc." },
    { symbol: "SRE", name: "Sempra" },
    { symbol: "OXY", name: "Occidental Petroleum" },
    { symbol: "D", name: "Dominion Energy Inc." },
    { symbol: "WMB", name: "Williams Companies Inc." },
    { symbol: "AEP", name: "American Electric Power" },
    { symbol: "AFL", name: "Aflac Inc." },
    { symbol: "MET", name: "MetLife Inc." },
    { symbol: "TFC", name: "Truist Financial Corp." },
    { symbol: "KMB", name: "Kimberly-Clark Corp." },
    { symbol: "PCAR", name: "PACCAR Inc." },
    { symbol: "PSX", name: "Phillips 66" },
    { symbol: "CCI", name: "Crown Castle Inc." },
    { symbol: "CTAS", name: "Cintas Corporation" },
    { symbol: "SPG", name: "Simon Property Group" },
    { symbol: "ROST", name: "Ross Stores Inc." },
    { symbol: "HLT", name: "Hilton Worldwide" },
    { symbol: "DXCM", name: "DexCom Inc." },
    { symbol: "GM", name: "General Motors Company" },
    { symbol: "F", name: "Ford Motor Company" },
    { symbol: "ALL", name: "The Allstate Corp." },
    { symbol: "MNST", name: "Monster Beverage Corp." },
    { symbol: "OKE", name: "ONEOK Inc." },
    { symbol: "AIG", name: "American International Group" },
    { symbol: "KDP", name: "Keurig Dr Pepper Inc." },
    { symbol: "DLTR", name: "Dollar Tree Inc." },
    { symbol: "IDXX", name: "IDEXX Laboratories" },
    { symbol: "YUM", name: "Yum! Brands Inc." },
    { symbol: "GIS", name: "General Mills Inc." },
    { symbol: "WELL", name: "Welltower Inc." },
    { symbol: "CMG", name: "Chipotle Mexican Grill" },
    { symbol: "EW", name: "Edwards Lifesciences" },
    { symbol: "PCG", name: "PG&E Corporation" },
    { symbol: "A", name: "Agilent Technologies" },
    { symbol: "HAL", name: "Halliburton Company" },
    { symbol: "PRU", name: "Prudential Financial" },
    { symbol: "IQV", name: "IQVIA Holdings Inc." },
    { symbol: "AME", name: "AMETEK Inc." },
    { symbol: "VLO", name: "Valero Energy Corp." },
    { symbol: "MRVL", name: "Marvell Technology" },
    { symbol: "CTVA", name: "Corteva Inc." },
    { symbol: "DVN", name: "Devon Energy Corp." },
    { symbol: "OTIS", name: "Otis Worldwide Corp." },
    { symbol: "KMI", name: "Kinder Morgan Inc." },
    { symbol: "DD", name: "DuPont de Nemours" },
    { symbol: "HSY", name: "The Hershey Company" },
    { symbol: "EA", name: "Electronic Arts Inc." },
    { symbol: "BIIB", name: "Biogen Inc." },
    { symbol: "ON", name: "ON Semiconductor" },
    { symbol: "FAST", name: "Fastenal Company" },
    { symbol: "GEHC", name: "GE HealthCare" },
    { symbol: "FANG", name: "Diamondback Energy" },
    { symbol: "EXC", name: "Exelon Corporation" },
    { symbol: "VRSK", name: "Verisk Analytics" },
    { symbol: "CDW", name: "CDW Corporation" },
    { symbol: "STZ", name: "Constellation Brands" },
    { symbol: "BK", name: "Bank of New York Mellon" },
    { symbol: "ROP", name: "Roper Technologies" },
    { symbol: "XEL", name: "Xcel Energy Inc." },
    { symbol: "ODFL", name: "Old Dominion Freight" },
    { symbol: "DOW", name: "Dow Inc." },
    { symbol: "KEYS", name: "Keysight Technologies" },
    { symbol: "IT", name: "Gartner Inc." },
    { symbol: "EFX", name: "Equifax Inc." },
    { symbol: "HPQ", name: "HP Inc." },
    { symbol: "ANSS", name: "Ansys Inc." },
    { symbol: "LHX", name: "L3Harris Technologies" },
    { symbol: "KHC", name: "Kraft Heinz Company" },
    { symbol: "GLW", name: "Corning Inc." },
    { symbol: "CBRE", name: "CBRE Group Inc." },
    { symbol: "CTSH", name: "Cognizant Technology" },
    { symbol: "PPG", name: "PPG Industries Inc." },
    { symbol: "RMD", name: "ResMed Inc." },
    { symbol: "GPN", name: "Global Payments Inc." },
    { symbol: "CPRT", name: "Copart Inc." },
    { symbol: "WAB", name: "Westinghouse Air Brake" },
    { symbol: "ROK", name: "Rockwell Automation" },
    { symbol: "TTWO", name: "Take-Two Interactive" },
    { symbol: "TRGP", name: "Targa Resources" },
    { symbol: "WEC", name: "WEC Energy Group" },
    { symbol: "APTV", name: "Aptiv PLC" },
    { symbol: "HPE", name: "Hewlett Packard Enterprise" },
    { symbol: "AWK", name: "American Water Works" },
    { symbol: "IRM", name: "Iron Mountain Inc." },
    { symbol: "MTD", name: "Mettler-Toledo Int." },
    { symbol: "FIS", name: "Fidelity National Info" },
    { symbol: "TSCO", name: "Tractor Supply Co." },
    { symbol: "ACGL", name: "Arch Capital Group" },
    { symbol: "URI", name: "United Rentals Inc." },
    { symbol: "SBAC", name: "SBA Communications" },
    { symbol: "ES", name: "Eversource Energy" },
    { symbol: "CHD", name: "Church & Dwight Co." },
    { symbol: "AVB", name: "AvalonBay Communities" },
    { symbol: "BRO", name: "Brown & Brown Inc." },
    { symbol: "HUBB", name: "Hubbell Incorporated" },
    { symbol: "VICI", name: "VICI Properties Inc." },
    { symbol: "FITB", name: "Fifth Third Bancorp" },
    { symbol: "HIG", name: "Hartford Financial" },
    { symbol: "DOV", name: "Dover Corporation" },
    { symbol: "DTE", name: "DTE Energy Company" },
    { symbol: "ETR", name: "Entergy Corporation" },
    { symbol: "WTW", name: "Willis Towers Watson" },
    { symbol: "FE", name: "FirstEnergy Corp." },
    { symbol: "EBAY", name: "eBay Inc." },
    { symbol: "MPWR", name: "Monolithic Power Systems" },
    { symbol: "TROW", name: "T. Rowe Price Group" },
    { symbol: "PEG", name: "Public Service Enterprise" },
    { symbol: "PPL", name: "PPL Corporation" },
    { symbol: "SYY", name: "Sysco Corporation" },
    { symbol: "RF", name: "Regions Financial" },
    { symbol: "HBAN", name: "Huntington Bancshares" },
    { symbol: "IFF", name: "International Flavors" },
    { symbol: "STT", name: "State Street Corp." },
    { symbol: "ULTA", name: "Ulta Beauty Inc." },
    { symbol: "EXPD", name: "Expeditors Int'l" },
    { symbol: "BAX", name: "Baxter International" },
    { symbol: "ARE", name: "Alexandria Real Estate" },
    { symbol: "EQR", name: "Equity Residential" },
    { symbol: "NUE", name: "Nucor Corporation" },
    { symbol: "LUV", name: "Southwest Airlines" },
    { symbol: "DAL", name: "Delta Air Lines Inc." },
    { symbol: "UAL", name: "United Airlines Holdings" },
    { symbol: "AAL", name: "American Airlines Group" },
    { symbol: "MAR", name: "Marriott International" },
    { symbol: "RCL", name: "Royal Caribbean Group" },
    { symbol: "CCL", name: "Carnival Corporation" },
    { symbol: "WYNN", name: "Wynn Resorts Limited" },
    { symbol: "MGM", name: "MGM Resorts Int'l" },
    { symbol: "LVS", name: "Las Vegas Sands Corp." },
    { symbol: "SBUX", name: "Starbucks Corporation" },
    { symbol: "DPZ", name: "Domino's Pizza Inc." },
    { symbol: "DDOG", name: "Datadog Inc." },
    { symbol: "SNOW", name: "Snowflake Inc." },
    { symbol: "CRWD", name: "CrowdStrike Holdings" },
    { symbol: "ZS", name: "Zscaler Inc." },
    { symbol: "NET", name: "Cloudflare Inc." },
    { symbol: "TEAM", name: "Atlassian Corporation" },
    { symbol: "MDB", name: "MongoDB Inc." },
    { symbol: "DKNG", name: "DraftKings Inc." },
    { symbol: "COIN", name: "Coinbase Global Inc." },
    { symbol: "HOOD", name: "Robinhood Markets" },
    { symbol: "SQ", name: "Block Inc. (Square)" },
    { symbol: "SHOP", name: "Shopify Inc." },
    { symbol: "SPOT", name: "Spotify Technology" },
    { symbol: "SNAP", name: "Snap Inc." },
    { symbol: "PINS", name: "Pinterest Inc." },
    { symbol: "ROKU", name: "Roku Inc." },
    { symbol: "U", name: "Unity Software Inc." },
    { symbol: "RBLX", name: "Roblox Corporation" },
    { symbol: "PATH", name: "UiPath Inc." },
    { symbol: "PLTR", name: "Palantir Technologies" },
    { symbol: "SOFI", name: "SoFi Technologies" },
    { symbol: "RIVN", name: "Rivian Automotive" },
    { symbol: "LCID", name: "Lucid Group Inc." },
    { symbol: "NIO", name: "NIO Inc." },
    { symbol: "XPEV", name: "XPeng Inc." },
    { symbol: "LI", name: "Li Auto Inc." },
    { symbol: "BABA", name: "Alibaba Group" },
    { symbol: "JD", name: "JD.com Inc." },
    { symbol: "PDD", name: "PDD Holdings (Temu)" },
    { symbol: "BIDU", name: "Baidu Inc." },
    { symbol: "TSM", name: "Taiwan Semiconductor" },
    { symbol: "ASML", name: "ASML Holding NV" },
    { symbol: "TM", name: "Toyota Motor Corp." },
    { symbol: "SONY", name: "Sony Group Corporation" },
    { symbol: "SAP", name: "SAP SE" },
    { symbol: "NVO", name: "Novo Nordisk A/S" },
    { symbol: "AZN", name: "AstraZeneca PLC" },
    { symbol: "SNY", name: "Sanofi" },
    { symbol: "GSK", name: "GSK plc" },
    { symbol: "SHEL", name: "Shell plc" },
    { symbol: "BP", name: "BP p.l.c." },
    { symbol: "TTE", name: "TotalEnergies SE" },
    { symbol: "RIO", name: "Rio Tinto Group" },
    { symbol: "BHP", name: "BHP Group Limited" },
    { symbol: "VALE", name: "Vale S.A." },
    { symbol: "WBA", name: "Walgreens Boots Alliance" },
    { symbol: "PARA", name: "Paramount Global" },
    { symbol: "WBD", name: "Warner Bros. Discovery" },
    { symbol: "FOX", name: "Fox Corporation" },
    { symbol: "NWSA", name: "News Corp" },
    { symbol: "LULU", name: "Lululemon Athletica" },
    { symbol: "DECK", name: "Deckers Outdoor Corp." },
    { symbol: "TPR", name: "Tapestry Inc." },
    { symbol: "RL", name: "Ralph Lauren Corp." },
    { symbol: "ETSY", name: "Etsy Inc." },
    { symbol: "W", name: "Wayfair Inc." },
    { symbol: "CHWY", name: "Chewy Inc." },
    { symbol: "DASH", name: "DoorDash Inc." },
    { symbol: "UBER", name: "Uber Technologies" },
    { symbol: "LYFT", name: "Lyft Inc." },
    { symbol: "ZM", name: "Zoom Communications" },
    { symbol: "DOCU", name: "DocuSign Inc." },
    { symbol: "OKTA", name: "Okta Inc." },
    { symbol: "TWLO", name: "Twilio Inc." },
    { symbol: "SPLK", name: "Splunk Inc." },
    { symbol: "WDAY", name: "Workday Inc." },
    { symbol: "VEEV", name: "Veeva Systems Inc." },
    { symbol: "ZS", name: "Zscaler Inc." },
    { symbol: "BILL", name: "BILL Holdings Inc." },
    { symbol: "HUBS", name: "HubSpot Inc." },
    { symbol: "TTD", name: "The Trade Desk Inc." },
    { symbol: "ENPH", name: "Enphase Energy Inc." },
    { symbol: "SEDG", name: "SolarEdge Technologies" },
    { symbol: "FSLR", name: "First Solar Inc." },
    { symbol: "RUN", name: "Sunrun Inc." },
    { symbol: "PLUG", name: "Plug Power Inc." },
    { symbol: "BE", name: "Bloom Energy Corp." },
    { symbol: "MRNA", name: "Moderna Inc." },
    { symbol: "BNTX", name: "BioNTech SE" },
    { symbol: "DNA", name: "Ginkgo Bioworks" },
    { symbol: "CRSP", name: "CRISPR Therapeutics" },
    { symbol: "NTLA", name: "Intellia Therapeutics" },
    { symbol: "EDIT", name: "Editas Medicine" },
    { symbol: "BEAM", name: "Beam Therapeutics" },
    { symbol: "SGEN", name: "Seagen Inc." },
    { symbol: "ILMN", name: "Illumina Inc." },
    { symbol: "ALGN", name: "Align Technology" },
    { symbol: "MTCH", name: "Match Group Inc." },
    { symbol: "ABNB", name: "Airbnb Inc." },
    { symbol: "EXPE", name: "Expedia Group Inc." },
    { symbol: "TCOM", name: "Trip.com Group" },
    { symbol: "CPNG", name: "Coupang Inc." },
    { symbol: "SE", name: "Sea Limited" },
    { symbol: "GRAB", name: "Grab Holdings" },
    { symbol: "MELI", name: "MercadoLibre Inc." },
    { symbol: "NU", name: "Nu Holdings Ltd." },
    { symbol: "STNE", name: "StoneCo Ltd." },
    // --- ETFs & Index Funds ---
    { symbol: "SPY", name: "SPDR S&P 500 ETF" },
    { symbol: "QQQ", name: "Invesco QQQ Trust (Nasdaq-100)" },
    { symbol: "DIA", name: "SPDR Dow Jones ETF" },
    { symbol: "IWM", name: "iShares Russell 2000 ETF" },
    { symbol: "VTI", name: "Vanguard Total Stock Market ETF" },
    { symbol: "VOO", name: "Vanguard S&P 500 ETF" },
    { symbol: "VEA", name: "Vanguard FTSE Developed Markets ETF" },
    { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF" },
    { symbol: "GLD", name: "SPDR Gold Shares ETF" },
    { symbol: "SLV", name: "iShares Silver Trust" },
    { symbol: "TLT", name: "iShares 20+ Year Treasury ETF" },
    { symbol: "HYG", name: "iShares High Yield Corporate Bond ETF" },
    { symbol: "XLF", name: "Financial Select Sector SPDR" },
    { symbol: "XLK", name: "Technology Select Sector SPDR" },
    { symbol: "XLE", name: "Energy Select Sector SPDR" },
    { symbol: "XLV", name: "Health Care Select Sector SPDR" },
    { symbol: "XLI", name: "Industrial Select Sector SPDR" },
    { symbol: "XLP", name: "Consumer Staples Select Sector SPDR" },
    { symbol: "XLY", name: "Consumer Discretionary Select SPDR" },
    { symbol: "ARKK", name: "ARK Innovation ETF" },
    { symbol: "ARKG", name: "ARK Genomic Revolution ETF" },
    { symbol: "SOXX", name: "iShares Semiconductor ETF" },
    { symbol: "SMH", name: "VanEck Semiconductor ETF" },
    { symbol: "KWEB", name: "KraneShares CSI China Internet ETF" },
    { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF" },
    { symbol: "EFA", name: "iShares MSCI EAFE ETF" },
    // --- Crypto-related ---
    { symbol: "BTC-USD", name: "Bitcoin USD" },
    { symbol: "ETH-USD", name: "Ethereum USD" },
    { symbol: "SOL-USD", name: "Solana USD" },
    { symbol: "BNB-USD", name: "Binance Coin USD" },
    { symbol: "XRP-USD", name: "XRP USD" },
    { symbol: "ADA-USD", name: "Cardano USD" },
    { symbol: "DOGE-USD", name: "Dogecoin USD" },
    { symbol: "AVAX-USD", name: "Avalanche USD" },
    { symbol: "DOT-USD", name: "Polkadot USD" },
    { symbol: "MATIC-USD", name: "Polygon USD" },
];
